djangovue_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("games.urls"))
]

games/urls.py
from django.urls import path
from games.views import *

app_name = "games"
urlpatterns = [
    path('', HomeView.as_view(), name="homepage"),
    path('math-game/', MathGameView.as_view(), name="math-game"),
    path('anagram-game/', AnagramGameView.as_view(), name="anagram-game"),
    path('record-score/', record_score, name="record-score"),
    path('game-scores/', GameScoresView.as_view(), name='game-scores')
]

games/models.py
from django.db import models


class GameScore(models.Model):
    MATH = "MATH"
    ANAGRAM = "ANAGRAM"

    GAME_CHOICES = [
        (MATH, "Math Game"),
        (ANAGRAM, "Anagram Game")
    ]

    user_name = models.TextField()
    game = models.TextField(choices=GAME_CHOICES, default=MATH)
    score = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

games/views.py
import json
from django.views.generic import TemplateView
from django.http import JsonResponse
from games.models import GameScore


class HomeView(TemplateView):
    template_name = "home.html"


class MathGameView(TemplateView):
    template_name = "math-game.html"


class AnagramGameView(TemplateView):
    template_name = "anagram-game.html"


class GameScoresView(TemplateView):
    template_name = "game-scores.html"

    def get_context_data(self, **kwargs):
        context = super(GameScoresView, self).get_context_data(**kwargs)
        context['anagram_scores'] = GameScore.objects.filter(game__exact='ANAGRAM').order_by('-score')
        context['math_scores'] = GameScore.objects.filter(game__exact='MATH').order_by('-score')
        return context


def record_score(request):
    data = json.loads(request.body)

    user_name = data["user-name"]
    game = data["game"]
    score = data["score"]

    new_score = GameScore(user_name=user_name, game=game, score=score)
    new_score.save()

    response = {
        "success": True
    }

    return JsonResponse(response)

templates/_base.html
<!DOCTYPE html>
<html lang="en">
{% block html %}

  <head>
    {% block head %}
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>
        {% block title %}{% endblock %} | Games
      </title>
    {% endblock %}
  </head>

  <body>
    {% block body %}
      <header>
        <nav>
          <a href="{% url 'games:homepage' %}">Home</a> |
          <a href="{% url 'games:math-game' %}">Math Game</a> |
          <a href="{% url 'games:anagram-game' %}">Anagram Game</a> |
          <a href="{% url 'games:game-scores' %}">Game Scores</a>
        </nav>
      </header>
      {% block main %}{% endblock %}
    {% endblock %}
  </body>
{% endblock %}
</html>

templates/_base_vue.html
{% extends '_base.html' %}

{% block html %}
<html lang="en">
<head>
    {% block head %}
    {{ block.super }}
    {% endblock %}
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>

<body>
    {% block body %}
    {{ block.super }}
    <noscript>
        <strong>
            We're sorry but vue-games doesn't work
            properly without JavaScript enabled. Please enable it to continue.
        </strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
    {% endblock body %}
</body>
</html>
{% endblock html %}

templates/anagram-game.html
{% extends "_base.html" %}

{% block title %}
  Anagram Game
{% endblock %}


{% block main %}
  <h1>Anagram Game</h1>
  <p>This is the anagram game.</p>
  <form id="anagram-form">
    <div>
      <label for="user-name">Username</label>
      <input name="user-name" id="user-name"/>
    </div>
    <div>
      <label for="score">Score</label>
      <input name="score" type="number" id="score"/>
    </div>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <button type="submit" id="record-score">Record Score</button>
  </form>
  <style>
    div, label {
      padding: 0.2rem;
    }
  </style>
  <script>
    document.getElementById('anagram-form').addEventListener('submit', async (e) => {
      e.preventDefault()
      const userName = document.getElementById('user-name').value
      const score = document.getElementById('score').value
      const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value

      const data = {
        'user-name': userName,
        'score': score,
        'game': 'ANAGRAM',
      }

      try {
        const response = await fetch('/record-score/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrfToken,
          },
          body: JSON.stringify(data),
        })

        const result = await response.json()
        console.log(result)
      } catch (error) {
        console.error(error)
      }
    })
  </script>
{% endblock %}

templates/game-scores.html
{% extends "_base.html" %}

{% block title %}Game Scores{% endblock %}
{% block main %}
    <h1>Game Scores</h1>
    <h2>Math Game</h2>
    <ol>
        {% for score in math_scores %}
            <li>{{ score.score }}: ({{ score.user_name }} - {{ score.created }})</li>
        {% endfor %}
    </ol>

    <h2>Anagram Game</h2>
    <ol>
        {% for score in anagram_scores %}
            <li>{{ score.score }}: ({{ score.user_name }} - {{ score.created }})</li>
        {% endfor %}
    </ol>
{% endblock %}

templates/home.html
{% extends "_base_vue.html" %}

{% block title %}
    Home
{% endblock %}

{% block main %}
    <h1>
        Home
    </h1>
{% endblock %}

templates/math-game.html
{% extends "_base_vue.html" %}

{% block title %}
    Math-Game
{% endblock %}

{% block main %}
    <h1>
        Math-Game
    </h1>
{% endblock %}